"""Cross-validation tests: astrojax access vs Brahe v1.1.2.

Uses a shared ECEF trajectory (from Brahe's SGP4) with Hermite interpolation
and float64 to isolate the access algorithm from propagation/frame errors.

Fixture data: tests/fixtures/access_brahe_trajectory.npz
Generated by: tests/fixtures/generate_access_brahe_fixtures.py
"""

from pathlib import Path

import jax.numpy as jnp
import numpy as np
import pytest

from astrojax.access import find_access_windows, ground_location
from astrojax.access.constraints import (
    constraint_all,
    elevation_constraint,
    off_nadir_constraint,
)
from astrojax.config import set_dtype
from astrojax.utils.interpolation import make_hermite_position_fn

# ---------------------------------------------------------------------------
# Tolerances
# ---------------------------------------------------------------------------

_TIME_TOL = 0.05  # seconds — both algorithms refine to ~0.01s
_DURATION_TOL = 0.1  # seconds

# ---------------------------------------------------------------------------
# Fixture path
# ---------------------------------------------------------------------------

_FIXTURE_PATH = Path(__file__).parent.parent / "fixtures" / "access_brahe_trajectory.npz"


@pytest.fixture(scope="module")
def fixture_data():
    """Load the Brahe fixture and build Hermite interpolated position function.

    Sets dtype to float64 for the duration of this module.
    """
    set_dtype(jnp.float64)

    data = np.load(_FIXTURE_PATH)

    times = jnp.array(data["times_s"], dtype=jnp.float64)
    positions = jnp.array(data["positions_ecef"], dtype=jnp.float64)
    velocities = jnp.array(data["velocities_ecef"], dtype=jnp.float64)

    pos_fn = make_hermite_position_fn(times, positions, velocities)

    loc = ground_location(
        lon=float(data["station_lon_deg"]),
        lat=float(data["station_lat_deg"]),
        alt=0.0,
        use_degrees=True,
    )

    return {
        "pos_fn": pos_fn,
        "loc": loc,
        "t_start": 0.0,
        "t_end": float(times[-1]),
        "data": data,
    }


# ═══════════════════════════════════════════════
# Baseline access: elevation-only constraints
# ═══════════════════════════════════════════════


class TestBaselineAccessVsBrahe:
    """Compare astrojax elevation-only access against Brahe."""

    def test_elevation_0deg_window_count(self, fixture_data):
        """el >= 0: must find exactly 15 windows."""
        windows = find_access_windows(
            fixture_data["pos_fn"],
            fixture_data["loc"],
            fixture_data["t_start"],
            fixture_data["t_end"],
            dt=10.0,
            constraint_fn=elevation_constraint(0.0),
        )
        expected_count = len(fixture_data["data"]["el0_t_rise"])
        assert len(windows) == expected_count, (
            f"Expected {expected_count} windows, got {len(windows)}"
        )

    def test_elevation_0deg_boundaries(self, fixture_data):
        """el >= 0: rise/set/duration within tolerance of Brahe."""
        windows = find_access_windows(
            fixture_data["pos_fn"],
            fixture_data["loc"],
            fixture_data["t_start"],
            fixture_data["t_end"],
            dt=10.0,
            constraint_fn=elevation_constraint(0.0),
        )

        data = fixture_data["data"]
        brahe_rise = data["el0_t_rise"]
        brahe_set = data["el0_t_set"]
        brahe_dur = data["el0_duration"]

        for i, w in enumerate(windows):
            assert abs(w.t_rise - brahe_rise[i]) < _TIME_TOL, (
                f"Window {i} rise: astrojax={w.t_rise:.2f}, brahe={brahe_rise[i]:.2f}"
            )
            assert abs(w.t_set - brahe_set[i]) < _TIME_TOL, (
                f"Window {i} set: astrojax={w.t_set:.2f}, brahe={brahe_set[i]:.2f}"
            )
            assert abs(w.duration - brahe_dur[i]) < _DURATION_TOL, (
                f"Window {i} dur: astrojax={w.duration:.2f}, brahe={brahe_dur[i]:.2f}"
            )

    def test_elevation_5deg_window_count(self, fixture_data):
        """el >= 5: must find exactly 15 windows."""
        windows = find_access_windows(
            fixture_data["pos_fn"],
            fixture_data["loc"],
            fixture_data["t_start"],
            fixture_data["t_end"],
            dt=10.0,
            constraint_fn=elevation_constraint(jnp.deg2rad(5.0)),
        )
        expected_count = len(fixture_data["data"]["el5_t_rise"])
        assert len(windows) == expected_count, (
            f"Expected {expected_count} windows, got {len(windows)}"
        )

    def test_elevation_5deg_boundaries(self, fixture_data):
        """el >= 5: rise/set/duration within tolerance of Brahe."""
        windows = find_access_windows(
            fixture_data["pos_fn"],
            fixture_data["loc"],
            fixture_data["t_start"],
            fixture_data["t_end"],
            dt=10.0,
            constraint_fn=elevation_constraint(jnp.deg2rad(5.0)),
        )

        data = fixture_data["data"]
        brahe_rise = data["el5_t_rise"]
        brahe_set = data["el5_t_set"]
        brahe_dur = data["el5_duration"]

        for i, w in enumerate(windows):
            assert abs(w.t_rise - brahe_rise[i]) < _TIME_TOL, (
                f"Window {i} rise: astrojax={w.t_rise:.2f}, brahe={brahe_rise[i]:.2f}"
            )
            assert abs(w.t_set - brahe_set[i]) < _TIME_TOL, (
                f"Window {i} set: astrojax={w.t_set:.2f}, brahe={brahe_set[i]:.2f}"
            )
            assert abs(w.duration - brahe_dur[i]) < _DURATION_TOL, (
                f"Window {i} dur: astrojax={w.duration:.2f}, brahe={brahe_dur[i]:.2f}"
            )


# ═══════════════════════════════════════════════
# Constraint-based access
# ═══════════════════════════════════════════════


class TestConstraintAccessVsBrahe:
    """Compare astrojax constraint access against Brahe."""

    def test_off_nadir_window_count(self, fixture_data):
        """off-nadir <= 60: window count matches Brahe."""
        windows = find_access_windows(
            fixture_data["pos_fn"],
            fixture_data["loc"],
            fixture_data["t_start"],
            fixture_data["t_end"],
            dt=10.0,
            constraint_fn=off_nadir_constraint(jnp.deg2rad(60.0)),
        )
        expected_count = len(fixture_data["data"]["on60_t_rise"])
        assert len(windows) == expected_count, (
            f"Expected {expected_count} windows, got {len(windows)}"
        )

    def test_off_nadir_boundaries(self, fixture_data):
        """off-nadir <= 60: boundaries within tolerance of Brahe."""
        windows = find_access_windows(
            fixture_data["pos_fn"],
            fixture_data["loc"],
            fixture_data["t_start"],
            fixture_data["t_end"],
            dt=10.0,
            constraint_fn=off_nadir_constraint(jnp.deg2rad(60.0)),
        )

        data = fixture_data["data"]
        brahe_rise = data["on60_t_rise"]
        brahe_set = data["on60_t_set"]
        brahe_dur = data["on60_duration"]

        for i, w in enumerate(windows):
            assert abs(w.t_rise - brahe_rise[i]) < _TIME_TOL, (
                f"Window {i} rise: astrojax={w.t_rise:.2f}, brahe={brahe_rise[i]:.2f}"
            )
            assert abs(w.t_set - brahe_set[i]) < _TIME_TOL, (
                f"Window {i} set: astrojax={w.t_set:.2f}, brahe={brahe_set[i]:.2f}"
            )
            assert abs(w.duration - brahe_dur[i]) < _DURATION_TOL, (
                f"Window {i} dur: astrojax={w.duration:.2f}, brahe={brahe_dur[i]:.2f}"
            )

    def test_composed_constraint_window_count(self, fixture_data):
        """el >= 5 AND off-nadir <= 60: window count matches Brahe."""
        combined = constraint_all(
            elevation_constraint(jnp.deg2rad(5.0)),
            off_nadir_constraint(jnp.deg2rad(60.0)),
        )
        windows = find_access_windows(
            fixture_data["pos_fn"],
            fixture_data["loc"],
            fixture_data["t_start"],
            fixture_data["t_end"],
            dt=10.0,
            constraint_fn=combined,
        )
        expected_count = len(fixture_data["data"]["combined_t_rise"])
        assert len(windows) == expected_count, (
            f"Expected {expected_count} windows, got {len(windows)}"
        )

    def test_composed_constraint_boundaries(self, fixture_data):
        """el >= 5 AND off-nadir <= 60: boundaries within tolerance of Brahe."""
        combined = constraint_all(
            elevation_constraint(jnp.deg2rad(5.0)),
            off_nadir_constraint(jnp.deg2rad(60.0)),
        )
        windows = find_access_windows(
            fixture_data["pos_fn"],
            fixture_data["loc"],
            fixture_data["t_start"],
            fixture_data["t_end"],
            dt=10.0,
            constraint_fn=combined,
        )

        data = fixture_data["data"]
        brahe_rise = data["combined_t_rise"]
        brahe_set = data["combined_t_set"]
        brahe_dur = data["combined_duration"]

        for i, w in enumerate(windows):
            assert abs(w.t_rise - brahe_rise[i]) < _TIME_TOL, (
                f"Window {i} rise: astrojax={w.t_rise:.2f}, brahe={brahe_rise[i]:.2f}"
            )
            assert abs(w.t_set - brahe_set[i]) < _TIME_TOL, (
                f"Window {i} set: astrojax={w.t_set:.2f}, brahe={brahe_set[i]:.2f}"
            )
            assert abs(w.duration - brahe_dur[i]) < _DURATION_TOL, (
                f"Window {i} dur: astrojax={w.duration:.2f}, brahe={brahe_dur[i]:.2f}"
            )


# ═══════════════════════════════════════════════
# Sanity checks: constraints narrow windows
# ═══════════════════════════════════════════════


class TestConstraintNarrowsWindows:
    """Verify constraint relationships hold."""

    def test_higher_elevation_narrows(self, fixture_data):
        """5-degree elevation windows should be shorter than 0-degree windows."""
        data = fixture_data["data"]
        dur_el0 = data["el0_duration"]
        dur_el5 = data["el5_duration"]

        # Same window count, but each 5-deg window is shorter
        assert len(dur_el0) == len(dur_el5)
        for i in range(len(dur_el0)):
            assert dur_el5[i] < dur_el0[i] + 0.1, (
                f"Window {i}: el5 duration ({dur_el5[i]:.1f}s) should be "
                f"shorter than el0 ({dur_el0[i]:.1f}s)"
            )

    def test_composed_narrows(self, fixture_data):
        """AND-composed windows are subsets of individual constraint windows.

        Each combined window (el >= 5 AND off-nadir <= 60) must be contained
        within some el >= 5 window and some off-nadir <= 60 window.
        """
        data = fixture_data["data"]
        combined_rise = data["combined_t_rise"]
        combined_set = data["combined_t_set"]
        el5_rise = data["el5_t_rise"]
        el5_set = data["el5_t_set"]
        on60_rise = data["on60_t_rise"]
        on60_set = data["on60_t_set"]

        for i in range(len(combined_rise)):
            cr, cs = combined_rise[i], combined_set[i]

            # Must be contained in some el >= 5 window
            contained_in_el5 = any(
                er <= cr + _TIME_TOL and es >= cs - _TIME_TOL
                for er, es in zip(el5_rise, el5_set, strict=True)
            )
            assert contained_in_el5, (
                f"Combined window {i} [{cr:.1f}, {cs:.1f}] not contained in any el >= 5 window"
            )

            # Must be contained in some off-nadir <= 60 window
            contained_in_on60 = any(
                or_ <= cr + _TIME_TOL and os_ >= cs - _TIME_TOL
                for or_, os_ in zip(on60_rise, on60_set, strict=True)
            )
            assert contained_in_on60, (
                f"Combined window {i} [{cr:.1f}, {cs:.1f}] not contained "
                f"in any off-nadir <= 60 window"
            )
